# Configuration needed to make the ADR plugin work

# Backend configuration: setup the github integration
#   https://backstage.io/docs/integrations/
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

# Local Janus configuration
# Frontned plugin configuration: provides the ADR information in the "Overview" tab
dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    adr-wrapper:
      mountPoints:
        - mountPoint: entity.page.overview/cards
          importName: EntityAdrContent
          config:
            layout:
              gridColumn: "1 / -1"

# RHDH configuration
# Frontned plugin configuration: provides the ADR information in the "Overview" tab
  plugins:
    # ...
    # Existing dynamic packages
    # ...

    - package: '<Location_of_adr_wrapper>'
      disabled: false
      integrity: 'ADR_WRAPPER_HASH'
      pluginConfig:
        dynamicPlugins:
          frontend:
            adr-wrapper:
              mountPoints:
                - mountPoint: entity.page.overview/cards
                  importName: EntityAdrContent
                  config:
                    layout:
                      gridColumn: "1 / -1" 