---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
stringData:
  BACKEND_SECRET: "${RHDH_BACKEND_SECRET}"
  HOST_URL: "${RHDH_HOST}"
  AUTH_GITHUB_CLIENT_ID: "${RHDH_AUTH_GITHUB_CLIENT_ID}"
  AUTH_GITHUB_CLIENT_SECRET: "${RHDH_AUTH_GITHUB_CLIENT_SECRET}"
  AUTH_GOOGLE_CLIENT_ID: "${RHDH_AUTH_GOOGLE_CLIENT_ID}"
  AUTH_GOOGLE_CLIENT_SECRET: "${RHDH_AUTH_GOOGLE_CLIENT_SECRET}"
  GITHUB_TOKEN: "${RHDH_GITHUB_TOKEN}"
  #GITHUB_APP_ID: "${RHDH_GITHUB_APP_ID}"
  #GITHUB_APP_CLIENT_ID: "${RHDH_GITHUB_APP_CLIENT_ID}"
  #GITHUB_APP_CLIENT_SECRET: "${RHDH_GITHUB_APP_CLIENT_SECRET}"
  #GITHUB_APP_WEBHOOK_URL: "${RHDH_GITHUB_APP_WEBHOOK_URL}"
  #GITHUB_APP_WEBHOOK_SECRET: "${RHDH_GITHUB_APP_WEBHOOK_SECRET}"
  GITHUB_ORG: "${RHDH_GITHUB_ORG}"
  GITHUB_ORG_URL: "${RHDH_GITHUB_ORG_URL}"
  K8S_CLUSTER_URL: "${RHDH_K8S_CLUSTER_URL}"
  K8S_SA_TOKEN: "${RHDH_K8S_SA_TOKEN}"
type: Opaque


---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-db-secret
  #name: backstage-psql-secret
stringData:
  POSTGRESQL_ADMIN_PASSWORD: "${RHDH_POSTGRESQL_ADMIN_PASSWORD}"
  POSTGRES_PASSWORD: "${RHDH_POSTGRES_PASSWORD}"
  POSTGRES_USER: "${RHDH_POSTGRES_USER}"
  POSTGRES_HOST: "${RHDH_POSTGRES_HOST}"
  POSTGRES_PORT: "${RHDH_POSTGRES_PORT}"
type: Opaque


# Not using the private file atm
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: rhdh-secrets-private-file
#data:
#  GITHUB_APP_PRIVATE_KEY_FILE: "${RHDH_GITHUB_APP_PRIVATE_KEY_FILE}"
#type: Opaque

