app:
  title: Janus IDP Backstage Showcase - Dynamic plugins
  baseUrl: http://localhost:3000

proxy:
 skipInvalidProxies: true
 endpoints: {}

dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    test-s3-viewer-wrapper:
      dynamicRoutes:
        - importName: S3ViewerPage
          menuItem:
            text: "s3 viewer"
            icon: SiAmazons3
          path: /s3-viewer


auth:
  environment: development
  session:
    secret: "${SESSION_SECRET}"
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, Group, Resource, Location, Template, API]
  locations:
    # Note: integrations.github[].apps must be correctly configured to read GitHub locations
    - type: file
      target: ../../catalog-entities/all.yaml


