---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-config-auth
data:
  rhdh-config.auth.yml: |
    signInPage: github
    auth:
      environment: production
      session:
       secret: ${AUTH_SESSION_SECRET}
      providers:
        github:
          production:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-config-main
data:
  rhdh-config.main.yml: |

    app:
      title: "RHDH AppEng Demo"
      baseUrl: ${HOST_URL}
      branding:
        theme:
          light:
            # primaryColor: '#38be8b'
            headerColor1: 'hsl(204 100% 71%)'
            headerColor2: 'color(a98-rgb 1 0 0)'
          dark:
            # primaryColor: '#ab75cf'
            headerColor1: '#0000d0'
            headerColor2: 'rgb(255 246 140)'

    backend:
      baseUrl: "${HOST_URL}"
      cors:
        origin: "${HOST_URL}"
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
      auth:
        keys:
          - secret: "${BACKEND_SECRET}"

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    techdocs:
      builder: "local"
      generator:
        runIn: "local"
      publisher:
        type: "local"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-config-catalog
data:
  rhdh-config.catalog.yml: |

    catalog:
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain]
      providers:
        githubOrg:
          githubUrl: "${GITHUB_ORG_URL}"
      locations:
        # Catalog and API entries - Janus entities
        - type: url
          target: https://github.com/janus-idp/backstage-showcase/blob/main/catalog-entities/all.yaml

        # All the templates (shows up in Create...) - Red Hat Developer Hub Software Templates location
        - type: url
          target: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates.yaml


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-config-dynamic-plugins
data:
  # The name of the yaml file has to be "dynamic-plugins.yaml"
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml

    plugins:
      - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-rbac'
        disabled: false
