apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
spec:
  database:
    enableLocalDb: true
  #  authSecretName: rhdh-db-secret
  application:
    replicas: 1
    appConfig:
      configMaps:
        - name: rhdh-config-main
        - name: rhdh-config-auth
        - name: rhdh-config-catalog
      mountPath:  /opt/app-root/src
    dynamicPluginsConfigMapName: rhdh-config-dynamic-plugins
    extraEnvs:
      secrets:
        - name: rhdh-secrets
    extraFiles:
      configMaps:
        - name: rhdh-config-rbac-policy    
      mountPath: /opt/app-root/src
