spec:
  application:
    appConfig:
      configMaps:
        - name: rhdh-config-main
        - name: rhdh-config-catalog    
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: rhdh-dynamic-plugins
    extraEnvs:
      secrets:
        - name: rhdh-secrets
    extraFiles:
      configMaps:
        - name: rhdh-config-rbac-policy    
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
